### ISSUE TITLE
 Question about checkpoint loading

### ISSUE THREAD

**Issue by MK-D-Luffy** [pairlab/QueST#11]
Hello! I have a question regarding checkpoint loading. I'm using libero10 for fine-tuning, but the checkpoint path in libero10 is set to LIBERO_10/quest/final/block_32_ds_4/0/stage_2/../stage_1. However, I previously pre-trained using libero90, so all the pre-trained model checkpoints are located in LIBERO_90/quest/final/block_32_ds_4/0/stage_1. This prevents me from loading the checkpoint directly. Currently, I’m moving the checkpoint from LIBERO_90 to LIBERO_10 to make it work. Is this a reasonable approach?

Thank you for your help!

**Comment by atharvamete** [comment]
Just an heads up, the latest commit should resolve this.
