### ISSUE TITLE
Few-shot unseen task setting

### ISSUE THREAD

**Issue by jis3613** [pairlab/QueST#12]
Hi, thanks for providing remarkable work!

It seems that 'finetune.sh' uses 'train_fewshot.yaml' configuration which I guess is used for the few-shot transfer unseen task experiment in Sec.5.3.

However, I could not find any parameters related to few-shot transfer in 'train_fewshot.yaml' or in 'train_base.yaml'.
Could you guide me how to configure the few-shot transfer setting ?

I find there is a 'libero_long_fewshot.yaml'.

Do I just change the task like this ?

python train.py --config-name=train_fewshot.yaml \
    task=libero_long_fewshot \
    ...
   
Thanks

**Comment by atharvamete** [comment]
Hi, yes the task should be libero_long_fewshot
Thanks for pointing this out. I'll update the example scripts.

**Comment by jis3613** [comment]
I get a following error when I run the updated few-shot transfer script.

`[info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

============= Initialized Observation Utils with Obs Spec =============

using obs modality: rgb with keys: ['eye_in_hand_rgb', 'agentview_rgb']
using obs modality: low_dim with keys: ['gripper_states', 'joint_states', 'ee_pos']
  0%|                                                                                                                                                                                                                                                                  | 0/10 [00:00<?, ?it/s]
Error executing job with overrides: ['task=libero_long_fewshot', 'algo=quest', 'exp_name=final', 'variant_name=block_32_ds_4', 'training.use_tqdm=false', 'training.save_all_checkpoints=true', 'training.use_amp=false', 'train_dataloader.persistent_workers=true', 'train_dataloader.num_workers=6', 'make_unique_experiment_dir=true', 'algo.skill_block_size=32', 'algo.downsample_factor=4', 'algo.l1_loss_scale=10', 'training.auto_continue=true', 'rollout.num_parallel_envs=5', 'rollout.rollouts_per_env=5', 'seed=0']
Error in call to target 'quest.utils.libero_utils.build_dataset':
AssertionError('asking for more demos than available in the dataset')
full_key: task.dataset
`

**Comment by atharvamete** [comment]
Hi, I just pushed some changes that should resolve this error, feel free to cherry pick latest commit.

**Comment by jis3613** [comment]
Thank you! Now it works!

**Comment by jis3613** [comment]
Hi, one more quick question !

If I want to change the number of shots in the few-shot setting, for example, if I want to do 10-shot transfer,
do I only need to change the 'demos_per_env' in the 'libero_long_fewshot.yaml'?

**Comment by atharvamete** [comment]
yes, that should work
