### ISSUE TITLE
Load Pre-trained Checkpoint in Finetune Script

### ISSUE THREAD

**Issue by TousakaNagio** [pairlab/QueST#4]
Hi,

Thank you for your excellent work.

If I want to fintune the multitasks on the LIBERO_long, how can I initialize the model from the checkpoint trained in Stage 0&1 on LIBERO_90? Because the code only initialize model weight from same task folder. BTW, where to download the LIBERO_long dataset or did you mean LIBERO_10?

**Comment by atharvamete** [comment]
Hi, thanks for your kind words!

There are two ways:
1. Use training.auto_continue=true, this will load the model from previous stage. This requires you to run the experiments with make_unique_experiment_dir=false (note this is true by default and hence will create 00x folders).
2. Just pass the checkpoint_path argument. This gives you flexibility to pass checkpoint from any previous stage/experiment.

Yes, LIBERO_long is LIBERO_10

**Comment by TousakaNagio** [comment]
Hi @atharvamete,

Thank you for your reply! It really helps for me.
I have tried to run the training script for stage 0 and stage 1. Then I finetuned the model on LIBERO_long. I got a success rate of 78.6% after evaluation which is much higher than the number reported in your paper figure 2(c). Is this a reasonable result?

**Comment by atharvamete** [comment]
Yes, this is a reasonable number, only the results in figure 2(c) are from our old implementation (which consistently gives low success rate for all methods. We plan to update that plot in camera ready version. Will report final numbers here as well.
Thanks!

**Comment by TousakaNagio** [comment]
In the current released code, the default history observation window length is 1. I am also wondering if a longer window length results in a better performance?

**Comment by TousakaNagio** [comment]
Also, is it possible to get the goal image while running evaluation script?

**Comment by atharvamete** [comment]
Unfortunately no. You could perhaps get goal images from successful rollouts of quest policy and edit the respective [runner](https://github.com/pairlab/QueST/tree/main/quest/env_runner) files to send the goal image to policy.

> I am also wondering if a longer window length results in a better performance?

Feel free to try this out, the code should support it by setting `algo.dataset.frame_stack` param in the config. Though QueST as is with obs window 1 shows error correcting behavior (reaching for the object again when the grasp is missed)
