### ISSUE TITLE
`generate_metaworld_dataset.py` not working 

### ISSUE THREAD

**Issue by junh0cho** [pairlab/QueST#7]
following https://github.com/pairlab/QueST/issues/3, I faced 
`hydra.errors.MissingConfigException: In 'collect_data': Could not find 'task/metaworld_ml45'`

therefore, changed `collect_daata.yaml` to have ` task: metaworld_ml45_prise ` 

then I get, 

```
  File "/home/junho/workspace/QueST/quest/utils/metaworld_utils.py", line 209, in expert
    obs_gt = obs['obs_gt'].squeeze()
KeyError: 'obs_gt'

# obs seemingly does not have obs_gt
(Pdb) obs.keys()
dict_keys(['corner_rgb', 'robot_states'])
(Pdb) n
KeyError: 'obs_gt'
```

How do I download metaworld dataset?
Thank you!

**Comment by atharvamete** [comment]
Did you cherry pick `cac6bb76090aa20e3bfb643f6ba74033f78991f1`? I had fixed this issue in that commit. Let me know if it still persists.

**Comment by junh0cho** [comment]
Oh, I have been using another repo of yours https://github.com/atharvamete/QueST
Changing to this repo and `main` branch works fine. Thank you!

**Comment by Gloriabhsfer** [comment]
hi, i have followed the cherrypick repo, but it returns me fatal: bad object cac6bb76090aa20e3bfb643f6ba74033f78991f1. I also got the obs_gt key error things. Could you please tell me how to solve this question?

**Comment by atharvamete** [comment]
@Gloriabhsfer Could you try the latest commit? It should resolve this.
