### ISSUE TITLE
Questions about training details 

### ISSUE THREAD

**Issue by MK-D-Luffy** [pairlab/QueST#9]
Hi,
Thanks for your great work!
I'm curious about the specific training details for  LIBERO-90 and MetaWorld . Could you kindly share the number of GPUs used for these tasks, as well as the duration of training for each?
Your insights would be invaluable to me, thanks a lot!

**Comment by atharvamete** [comment]
Thanks, all the experiments with default config should work on single 24GB GPU, we have tried V100, A100, and RTX_6000.

**Comment by atharvamete** [comment]
The parameters written in the config files should give the reported success rate. Which checkpoint are you using for evaluation? We found earlier ones ~20 to perform better than later ones on libero-90. For reference these are the results for 4 different seeds: [0.87888889, 0.88622222, 0.89277778, 0.88577778]

**Comment by MK-D-Luffy** [comment]
I trained an autoencoder for 100 epochs, then trained the prior for an additional 20 epochs before testing. The results were 85 and 86. My training setup used an RTX 3090 with a batch size of 512, and all other configurations remained unchanged.
